[tool.cibuildwheel]
before-all = "uname -a"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sf-pyrotel"
version = "0.0.1"
requires-python = ">=3.6"
