[tool.cibuildwheel]
before-all = "uname -a"
manylinux-x86_64-image = "manylinux_2_28"

[build-system]
requires = ["setuptools >= 74.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sf-pyrotel"
version = "0.0.5"
requires-python = ">=3.6"
dynamic = ["description", "readme", "license", "authors", "classifiers", "optional-dependencies"]
