name: Build/Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Hatch
        run: pipx install hatch

      - name: Build all wheels
        env:
          GITHUB_API_TOKEN: ${{ secrets.AGENT_DOWNLOAD_TOKEN }}
        run: hatch run build:all

      - uses: actions/upload-artifact@v4
        with:
          name: pyrotel-wheels
          path: ./dist/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest

    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pyrotel-wheels
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: false
