name: CI

on: [push]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          # TODO: matrix test?
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pipx install hatch

      - name: Run tests
        env:
          GITHUB_API_TOKEN: ${{ secrets.AGENT_DOWNLOAD_TOKEN }}
        run: |
          PYTHON_ENV=$(echo ${{ matrix.python-version }} | sed -e 's/\.//')
          hatch run test.py${PYTHON_ENV}:pytest

      - name: Dump rotel agent logs on failure
        if: ${{ failure() }}
        run: tail -n 15 /tmp/rotel-agent.log

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Hatch
        run: pipx install hatch

      - name: Run lint
        run: hatch run lint:check

      - name: Check for invalid src imports
        shell: bash
        run: |
          PATTERN="^from src\..*import.*"

          # Find files matching the pattern, excluding .git directory
          # Using -E for extended regular expressions instead of -P for perl regex
          # -l flag makes grep only output filenames that match
          MATCHES=$(grep -r -l -E "$PATTERN" --exclude-dir=".git" src || true)

          if [ -n "$MATCHES" ]; then
            echo "::error::Found prohibited pattern matches in the following files:"
            echo "$MATCHES" | while read file; do
              echo "::error::$file"
              # Show the actual matches with line numbers, also using -E
              grep -n -E "$PATTERN" "$file" | while read match; do
                echo "::error::  $match"
              done
            done
            exit 1  # Fail the GitHub action
          else
            echo "Success: No prohibited pattern matches found!"
            exit 0  # Action succeeds
          fi
