name: CI

on: [push]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true

          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: mheffner

      - uses: actions/setup-python@v5
        with:
          # TODO: matrix test?
          python-version: "3.9"

      - name: Install Hatch
        run: pipx install hatch

      - name: Build
        env:
          GITHUB_API_TOKEN: ${{ secrets.AGENT_DOWNLOAD_TOKEN }}
        run: hatch run build:me

      - name: Run tests
        run: hatch run test:pytest

      - name: Dump rotel agent logs on failure
        if: ${{ failure() }}
        run: tail -n 15 /tmp/rotel-agent.log

#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-python@v5
#        # TODO: matrix test
#        python-version: "3.9"
#
#      - name: Install Hatch
#        run: pipx install hatch
#
#      - name: Run tests
#        run: hatch run lint:all
