name: CI

on: [push]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          # TODO: matrix test?
          python-version: "3.9"

      - name: Install Hatch
        run: pipx install hatch

      - name: Build
        env:
          GITHUB_API_TOKEN: ${{ secrets.AGENT_DOWNLOAD_TOKEN }}
        run: hatch run build:me

      - name: Run tests
        run: hatch run test:pytest

#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-python@v5
#        # TODO: matrix test
#        python-version: "3.9"
#
#      - name: Install Hatch
#        run: pipx install hatch
#
#      - name: Run tests
#        run: hatch run lint:all
